package quandoo.de.tests.positivetests;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

public class LoginPageTests {
  private WebDriver driver;

  JavascriptExecutor js;

  @Before
  public void setUp() throws InterruptedException {
    System.setProperty("webdriver.chrome.driver", "src\\main\\resources\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    driver.get("https://www.quandoo.de/en");
    driver.manage().window().setSize(new Dimension(1505, 992));
    driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
    Thread.sleep(3000);
    driver.findElement(By.linkText("Log in")).click();
  }

  @After
  public void tearDown() {
    driver.quit();
  }


  @Test
  public void login() throws InterruptedException {

    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("giosos2000@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("Qw150150+");
    driver.findElement(By.name("login")).click();
    driver.findElement(By.cssSelector(".nc-icon"));

  }

  @Test
  public void signUpNowInLogOnPage() {



    driver.findElement(By.linkText("Sign up now")).click();



  }
}