package quandoo.de.tests.positivetests;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class QundooreservnowTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  // Don't run this test after 22:00
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void qundooreservnow() throws InterruptedException {
    driver.get("https://www.quandoo.de/en/place/taleh-thai-6902");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
    Thread.sleep (2000);
    driver.findElement(By.cssSelector(".reservation-tab-btn")).click();
    assertThat(driver.findElement(By.cssSelector(".sc-1r67tf4-0")).getText(), is("Complete"));
    driver.close();
  }
}
