package quandoo.de.tests.positivetests;// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import quandoo.de.tests.BaseTest;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class RegistrationTest extends BaseTest {



  // Test for registration! If we change thr data in this field we can complete our registration!

  @Test
  public void registration() throws InterruptedException {
    driver.get("https://www.quandoo.de/en/place/taleh-thai-6902");
    driver.manage().window().setSize(new Dimension(1505, 992));
    driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
    Thread.sleep (2000);
    driver.findElement(By.linkText("Sign up")).click();
    driver.findElement(By.name("firstName")).click();

    //Firstname, Lastname and email must be edited for complete registration!

    driver.findElement(By.name("firstName")).sendKeys("Giorgi");
    driver.findElement(By.name("lastName")).sendKeys("Sosiashvili");
    driver.findElement(By.name("email")).sendKeys("giosos2000@gmail.com");

    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("Qw150150+");
    driver.findElement(By.name("password-confirm")).sendKeys("Qw150150+");
    driver.findElement(By.cssSelector(".sc-chPdSV.ejkbRc")).click();
    driver.findElement(By.name("register")).click();
    assertThat(driver.findElement(By.cssSelector(".sc-AxiKw > .cCHPAs")).getText(), is("Log out"));

  }
}
