package quandoo.de.tests.positivetests;// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import quandoo.de.tests.BaseTest;

public class SignUpNowInLogOnPageTest  extends BaseTest {

  //Test for registration if user has no account

  @Test
  public void signUpNowInLogOnPage() {
    driver.get("https://www.quandoo.de/en");
    driver.manage().window().setSize(new Dimension(1505, 992));
    driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
    driver.findElement(By.linkText("Log in")).click();
    driver.findElement(By.linkText("Sign up now")).click();

  }
}
