package quandoo.de.tests.negativetests;// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import quandoo.de.tests.BaseTest;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class LoginNegativeTest extends BaseTest {

  // Test for log in with wrong password

  @Test
  public void loginNegative() {
    driver.get("https://www.quandoo.de/en/place/taleh-thai-6902");
    driver.manage().window().setSize(new Dimension(1460, 992));
    driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
    driver.findElement(By.linkText("Log in")).click();
    driver.findElement(By.name("username")).click();
    driver.findElement(By.name("username")).sendKeys("giosos2000@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("Qw150150"); //Wrong password
    driver.findElement(By.name("login")).click();
    assertThat(driver.findElement(By.cssSelector(".Error__ErrorWrapper-jytvvh-0")).getText(), is("Enter valid username or password"));

  }
}
