package quandoo.de.tests.negativetests;// Generated by Selenium IDE

import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import quandoo.de.tests.BaseTest;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class RegistrationNegativeTest extends BaseTest {

  // Test for registration with existing account

  @Test
  public void registrationNegative() {
    driver.get("https://www.quandoo.de/en/place/taleh-thai-6902");
    driver.manage().window().setSize(new Dimension(1505, 992));
    driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
    driver.findElement(By.linkText("Sign up")).click();
    driver.findElement(By.name("firstName")).click();
    driver.findElement(By.name("firstName")).sendKeys("Giorgi");
    driver.findElement(By.name("lastName")).sendKeys("Sosiashvili");
    driver.findElement(By.name("email")).sendKeys("giosos2000@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("Qw150150+");
    driver.findElement(By.name("password-confirm")).sendKeys("Qw150150+");
    driver.findElement(By.cssSelector(".ConsentLinks__ConsentLinksWrapper-sc-2d9ofy-0")).click();
    driver.findElement(By.name("register")).click();
    assertThat(driver.findElement(By.cssSelector("#root > div > div > form > section > div:nth-child(6) > div > div > div")).getText(), is("Email already exists. Please use another."));

  }


}
