package quandoo.de.tests.negativetests;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class RegistrationNegativeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void registrationnegative() {
    driver.get("https://www.quandoo.de/en/place/taleh-thai-6902");
    driver.manage().window().setSize(new Dimension(1505, 992));
    driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
    driver.findElement(By.linkText("Sign up")).click();
    driver.findElement(By.name("firstName")).click();
    driver.findElement(By.name("firstName")).sendKeys("Giorgi");
    driver.findElement(By.name("lastName")).sendKeys("Sosiashvili");
    driver.findElement(By.name("email")).sendKeys("giosos2000@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("Qw150150+");
    driver.findElement(By.name("password-confirm")).sendKeys("Qw150150+");
    driver.findElement(By.cssSelector(".ConsentLinks__ConsentLinksWrapper-sc-2d9ofy-0")).click();
    driver.findElement(By.name("register")).click();
    assertThat(driver.findElement(By.cssSelector("#root > div > div > form > section > div:nth-child(6) > div > div > div")).getText(), is("Email already exists. Please use another."));
    driver.close();
  }


}
