package quandoo.de.base;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class ChangelanguageTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void changelanguage() throws InterruptedException {

    driver.manage().window().setSize(new Dimension(1744, 992));
    driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
    driver.findElement(By.xpath("//*[@id=\"root\"]/section/div[3]/div/div[2]/div/div[1]/header/div[4]/div/div[1]")).click();
    driver.findElement(By.linkText("Deutsch")).click();
    assertThat(driver.findElement(By.linkText("Anmelden")).getText(), is("Anmelden"));
    driver.close();
  }
}
